CREATE TABLE IF NOT EXISTS Users (
 	id SERIAL PRIMARY KEY,
 	name VARCHAR(255) NOT NULL,
	surname VARCHAR(255),
	email VARCHAR(255) UNIQUE NOT NULL,
	password VARCHAR(255) NOT NULL,
	created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
 	CONSTRAINT email_unique UNIQUE (email)
);
